/* fast_board — ultra-fast random legal chess position generator.
 *
 * Positions are generated by random legal-move walks from the start
 * position, so every FEN is reachable and legal.
 */
#ifndef BOARDGEN_H
#define BOARDGEN_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RBG_FEN_MAX 128
#define RBG_OK 0
#define RBG_ERR -1

/* Generate `n` random legal FENs via walks of [min_ply, max_ply] plies.
 * `out` must hold n * RBG_FEN_MAX bytes (row-major, each FEN NUL-terminated).
 * Returns number of FENs written (may be < n if walks hit dead ends and
 * retries are exhausted), or RBG_ERR on bad args.
 */
int rbg_generate_fens(
    char *out,
    int n,
    int min_ply,
    int max_ply,
    uint64_t seed,
    int skip_terminal
);

/* Same as above but writes into a flat C-string list with exact fen lengths
 * packed: each entry is RBG_FEN_MAX bytes.
 */
int rbg_generate_fens_ex(
    char *out,
    int n,
    int min_ply,
    int max_ply,
    uint64_t seed,
    int skip_terminal,
    int max_retries
);

/* Self-check: perft from startpos at given depth. Used for correctness. */
uint64_t rbg_perft(int depth);

/* Library version string. */
const char *rbg_version(void);

#ifdef __cplusplus
}
#endif

#endif /* BOARDGEN_H */
